### ISSUE TITLE
网速在0b和*kb之间变换的时候，会左右抖动

### ISSUE THREAD

**Issue by guozhiqiang123** [xmuli/lfxSpeed#10]
如题，由于文本宽度的变化导致抖动效果，非常吸引人的注意力，希望修复一下。我是直接在应用商店安装的，版本是0.6.4-1。

**Comment by xmuli** [comment]
你暂可以用 https://github.com/xmuli/NetSpeed ，在这里解决了  “文本宽度的变化导致抖动效果” 的问题。

**Comment by guozhiqiang123** [comment]
好的

**Comment by xmuli** [comment]
最近忙着开新坑在； 这个后面后面回过头再更新一版（立个 Flage 先）
