### ISSUE TITLE
关于任务栏显示的关闭建议

### ISSUE THREAD

**Issue by lk-timeout** [xmuli/lfxSpeed#2]
从目前的文档看，关闭的话，就是直接卸载。
有没有什么命令是可以控制是否在任务栏显示的？后续会增加这个功能的开发吗？
或者其实有，只是我不知道，我是linux小白，如果是简单的问题，不要喷我。

最后感谢作者提供的软件，很喜欢。

**Comment by xmuli** [comment]
谢谢你的喜欢；

无法关闭， 是因为
https://github.com/xmuli/lfxSpeed/blob/0028ef34726b3212c8b524b62c112eccdb2da1e1/speedplugin.cpp#L43-L47

因为故意和时间的返回名称一样了，所有会有此 bug。
目的是为了避免被上下压缩显示（将此处换一个名称，再然后自行编译，就可以在任务栏鼠标右键，显示或者关闭了）；

**缺陷二者选其一（1.2.2 dock 无法避免）：**
- 插件上下被压缩，遮盖显示不全（任务栏高度较低会触发）；但是可以自行隐藏或显示
- 插件完整显示（任务栏高度不限），但是会有无法隐藏 bug

详细分析参见： [Deepin 开发任务栏网速插件 lfxSpeed](https://xmuli.blog.csdn.net/article/details/110672252) 中  `任务栏 1.2.2 的缺陷` 一段
