### ISSUE TITLE
主题及默认配置

### ISSUE THREAD

**Issue by KINQIN** [xmuli/lfxSpeed#3]
浅色主题下，显示的字体颜色是浅蓝色，而且比较难看的清楚，是否有希望看到另一个颜色？
我在配置里把内存及CPU显示关闭，但重启系统后，它们又出现了，我该怎么做呢

**Comment by xmuli** [comment]
> 浅色主题下，显示的字体颜色是浅蓝色，而且比较难看的清楚，是否有希望看到另一个颜色？

这个后会新加功能，颜色可以改为自定义

> 我在配置里把内存及CPU显示关闭，但重启系统后，它们又出现了，我该怎么做呢

感谢反馈，linux 我一般不关机（很久才重启一次），且默配置是我的习惯；因为保存的数据没有写入到文本数据中，所以每次开机重启后会默认全部显示

**Comment by KINQIN** [comment]
多谢解答，期待新功能❤️



---原始邮件---
发件人: "偕臧"<notifications@github.com&gt;
发送时间: 2020年12月15日(周二) 中午1:22
收件人: "xmuli/lfxSpeed"<lfxSpeed@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"kinqin"<kinqin.pan@foxmail.com&gt;;
主题: Re: [xmuli/lfxSpeed] 主题及默认配置 (#3)




  
浅色主题下，显示的字体颜色是浅蓝色，而且比较难看的清楚，是否有希望看到另一个颜色？
  
这个后会新加功能，颜色可以改为自定义
  
我在配置里把内存及CPU显示关闭，但重启系统后，它们又出现了，我该怎么做呢
  
感谢反馈，linux 我一般不关机（很久才重启一次），且默配置是我的习惯；因为保存的数据没有写入到文本数据中，所以每次开机重启后会默认全部显示

**Comment by xmuli** [comment]
抽出时间，我会努力更新的。
