### ISSUE TITLE
网速计算不准确

### ISSUE THREAD

**Issue by iatneh** [xmuli/lfxSpeed#4]
找了很久终于找到这么一个插件，很是喜欢~
不过在使用过程中发现实时网速显示的不是很准确，在研究作者的源码后发现一处疑点
SpeedInfo::netRate方法中
![image](https://user-images.githubusercontent.com/2985793/102183517-f0e7f400-3ee8-11eb-9698-bdef39e92feb.png)

取的分别是下标为2和10的值，在我本地这两个值分别代表的是下载和上传的包数，而不是字节数。

![image](https://user-images.githubusercontent.com/2985793/102183489-e88fb900-3ee8-11eb-8fa5-86093ce58d38.png)

所以我猜测正确的取法应该是
down = list.at(1).toLong();
upload = list.at(9).toLong();

因为不是做c开发的，本地没有环境，所以提了这个Issue来向作者求解。

系统如下:
![image](https://user-images.githubusercontent.com/2985793/102183722-402e2480-3ee9-11eb-886a-e37e2534d594.png)

**Comment by xmuli** [comment]
**这里使用 QRegExp("\\s{1,}") 来分割，莫名会得到第一个切割为 “” 的字符串，所以对应的第 1和 9 列都要顺延加 1。**
但是切割其它文件，开头却正常没有空字符串。

详细参考 [Deepin 开发任务栏网速插件 lfxSpeed](https://xmuli.blog.csdn.net/article/details/110672252) 中  **获取网速** 一段，有讲解详细原因

PS：**结论：网速是正确的**， 如果和系统监视器的网速对比，会发现网速极其接近，但是数值略有差异。监视器采用没个 2 s 读取一次该文件，而我是没隔 1s读取一次此文件；然后计算差值（但是具体到某一时刻，毫秒单位的精度，两个读取是无法完全读取相同时刻的）

**Comment by iatneh** [comment]
![image](https://user-images.githubusercontent.com/2985793/102204189-80e76700-3f04-11eb-8e03-38bcd971038e.png)

实际测试的时候发现网速差异还是比较大的，插件里显示的速度基本上没有上过10KB

**Comment by iatneh** [comment]
下图是你博客里的截图，会不会是你的主要流量在lo enu1这两个网卡上导致的啊，这两个前面是有空格的
![image](https://user-images.githubusercontent.com/2985793/102205532-47176000-3f06-11eb-853d-4882752c38ea.png)

下图是我本地的，主要流量在wlp1s0和lo上面，其中wlp1s0前面没有空格，所以取到的数据不正确
![image](https://user-images.githubusercontent.com/2985793/102205669-76c66800-3f06-11eb-98b0-1f6cc72bb854.png)

**Comment by KINQIN** [comment]
同样遇到这个问题，我在使用FDM下载文件，网速没有显示到插件上

**Comment by xmuli** [comment]
@iatneh 很有可能，晚上用笔记本试一下，看来这是一个严重bug，周末解决一下

@KINQIN 你指的是，网速也一直显示速率一直很低吧？ 能否也提供一张 `sudo cat /proc/net/dev` 截图

**Comment by KINQIN** [comment]
![图片](https://user-images.githubusercontent.com/49337478/102436575-db430d80-4053-11eb-975f-553043d6cfbd.png)
@xmuli

**Comment by xmuli** [comment]
已经被另外一个贡献者修复：[v0.6](https://github.com/xmuli/lfxSpeed/releases/tag/v0.6) ，请更新这个再尝试一下
