### ISSUE TITLE
图表模式里面的样式能不能做个折线图模式 ?

### ISSUE THREAD

**Issue by forliuyifei** [xmuli/lfxSpeed#7]
就像 deepin 自带系统监视器里面的效果差不多.

现在用的柱形图, 老实说很鸡肋, 看不太出变化, 就那么一点点展示区域.

或者把这个折线图放在气泡里面, 方便观测.

**Comment by forliuyifei** [comment]
其实音乐频谱也是可以考虑加进去的.

**Comment by xmuli** [comment]
推荐重构版本，使用 [lfxNet](https://github.com/xmuli/lfxNet)；

你说的这个功能在开发中，有这个计划，不过看后面有多少时间；

![image](https://user-images.githubusercontent.com/33887845/106686575-80ff0b80-6605-11eb-8492-67c71936e723.png)
